# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from billsby_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    COMPANY_DOMAIN_CUSTOMERS = "/{companyDomain}/customers"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID = "/{companyDomain}/customers/{customerUniqueId}"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_SUBSCRIPTIONS = "/{companyDomain}/customers/{customerUniqueId}/subscriptions"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_SUBSCRIPTIONS_FEATURETAGS = "/{companyDomain}/customers/{customerUniqueId}/subscriptions/featuretags"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_INVOICES_INVOICE_NUMBER_PAYMENTLOGS = "/{companyDomain}/customers/{customerUniqueId}/invoices/{invoiceNumber}/paymentlogs"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_PAYMENTDETAILSREQUEST = "/{companyDomain}/customers/{customerUniqueId}/paymentdetailsrequest"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_PAYMENT_CARD = "/{companyDomain}/customers/{customerUniqueId}/paymentCard"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_INVOICES = "/{companyDomain}/customers/{customerUniqueId}/invoices"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_GDPRCLEANUP = "/{companyDomain}/customers/{customerUniqueId}/gdprcleanup"
    COMPANY_DOMAIN_SUBSCRIPTIONS = "/{companyDomain}/subscriptions"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID = "/{companyDomain}/subscriptions/{subscriptionUniqueId}"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_SHIPPING_ADDRESS = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/shippingAddress"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_TAGS = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/tags"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_TAGS_SPLIT = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/tags/split"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_LOGS = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/logs"
    COMPANY_DOMAIN_SUBSCRIPTIONS_TAGS = "/{companyDomain}/subscriptions/tags"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_PLAN = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/plan"
    COMPANY_DOMAIN_SUBSCRIPTIONS_TAGS_TAGNAME = "/{companyDomain}/subscriptions/tags/{tagname}"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_RENEWALDATE = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/renewaldate"
    INVOICES_INVOICE_NUMBER = "/invoices/{invoiceNumber}"
    COMPANY_DOMAIN_COMPANIES_INVOICES = "/{companyDomain}/companies/invoices"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_REFUNDS = "/{companyDomain}/customers/{customerUniqueId}/refunds"
    COMPANY_DOMAIN_INVOICES_INVOICE_NUMBER_PAYMENT = "/{companyDomain}/invoices/{invoiceNumber}/Payment"
    COMPANY_DOMAIN_INVOICES_INVOICE_NUMBER_PAID_OFFLINE = "/{companyDomain}/invoices/{invoiceNumber}/PaidOffline"
    COMPANY_DOMAIN_INVOICES_INVOICE_NUMBER_WRITTEN_OFF = "/{companyDomain}/invoices/{invoiceNumber}/WrittenOff"
    COMPANY_DOMAIN_COMPANIES_CREDITNOTES = "/{companyDomain}/companies/creditnotes"
    COMPANY_DOMAIN_CUSTOMERS_CUSTOMER_UNIQUE_ID_CREDIT_NOTES = "/{companyDomain}/customers/{customerUniqueId}/creditNotes"
    COMPANY_DOMAIN__CREDIT_NOTES__CREDIT_NOTE_NUMBER__PAYMENT = "/{companyDomain} /creditNotes /{creditNoteNumber} /Payment"
    COMPANY_DOMAIN_PRODUCTS_PRODUCT_ID = "/{companyDomain}/products/{productId}"
    COMPANY_DOMAIN_PRODUCTS = "/{companyDomain}/products"
    COMPANY_DOMAIN_PRODUCTS_PRODUCT_ID_PLANS = "/{companyDomain}/products/{productId}/plans"
    COMPANY_DOMAIN_PRODUCTS_PRODUCT_ID_PLANS_PLAN_ID_CYCLES = "/{companyDomain}/products/{productId}/plans/{planId}/cycles"
    COMPANY_DOMAIN_PRODUCTS_PRODUCT_ID_PLANS_PLAN_ID = "/{companyDomain}/products/{productId}/plans/{planId}"
    COMPANY_DOMAIN_PRODUCTS_PRODUCT_ID_PLANS_ORDERS = "/{companyDomain}/products/{productId}/plans/orders"
    USAGE_COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_COUNTERS_COUNTER_ID = "/usage/{companyDomain}/subscriptions/{subscriptionUniqueId}/counters/{counterId}"
    OPERATIONS_COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_COUNTERS_COUNTER_ID = "/operations/{companyDomain}/subscriptions/{subscriptionUniqueId}/counters/{counterId}"
    COMPANY_DOMAIN_ADDONS = "/{companyDomain}/addons"
    COMPANY_DOMAIN_ADDONS_ADDON_ID = "/{companyDomain}/addons/{addonId}"
    COMPANY_DOMAIN_ALLOWANCES = "/{companyDomain}/allowances"
    COMPANY_DOMAIN_ALLOWANCES_ALLOWANCE_ID = "/{companyDomain}/allowances/{allowanceId}"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_ADDONS = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/addons"
    COMPANY_DOMAIN_SUBSCRIPTIONS_SUBSCRIPTION_UNIQUE_ID_ALLOWANCES = "/{companyDomain}/subscriptions/{subscriptionUniqueId}/allowances"
    COMPANY_DOMAIN_CUSTOMFIELDS = "/{companyDomain}/customfields"
    COMPANY_DOMAIN_CUSTOMFIELDS_CUSTOM_FIELD_ID = "/{companyDomain}/customfields/{customFieldId}"
    COMPANY_DOMAIN_CUSTOMFIELD_RESPONSES = "/{companyDomain}/customfieldResponses"
    COMPANY_DOMAIN_CUSTOMFIELD_RESPONSES_CUSTOM_FIELD_RESPONSE_ID = "/{companyDomain}/customfieldResponses/{customFieldResponseId}"
