# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class CustomerGetSubscriptionsByUniqueIdResponseItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            subscriptionId = schemas.StrSchema
            productId = schemas.IntSchema
            productName = schemas.StrSchema
            planId = schemas.IntSchema
            planName = schemas.StrSchema
            status = schemas.StrSchema
            currency = schemas.StrSchema
            revenue = schemas.StrSchema
            nextBilling = schemas.StrSchema
            createdOn = schemas.StrSchema
            units = schemas.IntSchema
            __annotations__ = {
                "subscriptionId": subscriptionId,
                "productId": productId,
                "productName": productName,
                "planId": planId,
                "planName": planName,
                "status": status,
                "currency": currency,
                "revenue": revenue,
                "nextBilling": nextBilling,
                "createdOn": createdOn,
                "units": units,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscriptionId"]) -> MetaOapg.properties.subscriptionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["productId"]) -> MetaOapg.properties.productId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["productName"]) -> MetaOapg.properties.productName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["planId"]) -> MetaOapg.properties.planId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["planName"]) -> MetaOapg.properties.planName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["revenue"]) -> MetaOapg.properties.revenue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nextBilling"]) -> MetaOapg.properties.nextBilling: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdOn"]) -> MetaOapg.properties.createdOn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["units"]) -> MetaOapg.properties.units: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["subscriptionId", "productId", "productName", "planId", "planName", "status", "currency", "revenue", "nextBilling", "createdOn", "units", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscriptionId"]) -> typing.Union[MetaOapg.properties.subscriptionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["productId"]) -> typing.Union[MetaOapg.properties.productId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["productName"]) -> typing.Union[MetaOapg.properties.productName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["planId"]) -> typing.Union[MetaOapg.properties.planId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["planName"]) -> typing.Union[MetaOapg.properties.planName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> typing.Union[MetaOapg.properties.currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["revenue"]) -> typing.Union[MetaOapg.properties.revenue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nextBilling"]) -> typing.Union[MetaOapg.properties.nextBilling, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdOn"]) -> typing.Union[MetaOapg.properties.createdOn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["units"]) -> typing.Union[MetaOapg.properties.units, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["subscriptionId", "productId", "productName", "planId", "planName", "status", "currency", "revenue", "nextBilling", "createdOn", "units", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        subscriptionId: typing.Union[MetaOapg.properties.subscriptionId, str, schemas.Unset] = schemas.unset,
        productId: typing.Union[MetaOapg.properties.productId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        productName: typing.Union[MetaOapg.properties.productName, str, schemas.Unset] = schemas.unset,
        planId: typing.Union[MetaOapg.properties.planId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        planName: typing.Union[MetaOapg.properties.planName, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        currency: typing.Union[MetaOapg.properties.currency, str, schemas.Unset] = schemas.unset,
        revenue: typing.Union[MetaOapg.properties.revenue, str, schemas.Unset] = schemas.unset,
        nextBilling: typing.Union[MetaOapg.properties.nextBilling, str, schemas.Unset] = schemas.unset,
        createdOn: typing.Union[MetaOapg.properties.createdOn, str, schemas.Unset] = schemas.unset,
        units: typing.Union[MetaOapg.properties.units, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CustomerGetSubscriptionsByUniqueIdResponseItem':
        return super().__new__(
            cls,
            *args,
            subscriptionId=subscriptionId,
            productId=productId,
            productName=productName,
            planId=planId,
            planName=planName,
            status=status,
            currency=currency,
            revenue=revenue,
            nextBilling=nextBilling,
            createdOn=createdOn,
            units=units,
            _configuration=_configuration,
            **kwargs,
        )
