# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class CustomerUpdateDetailsRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "firstName",
            "lastName",
            "billingAddress",
            "email",
        }
        
        class properties:
            firstName = schemas.StrSchema
            lastName = schemas.StrSchema
            email = schemas.StrSchema
        
            @staticmethod
            def billingAddress() -> typing.Type['CustomerUpdateDetailsRequestBillingAddress']:
                return CustomerUpdateDetailsRequestBillingAddress
            phoneNumberDialCountry = schemas.StrSchema
            phoneNumberDialCode = schemas.StrSchema
            phoneNumber = schemas.StrSchema
            __annotations__ = {
                "firstName": firstName,
                "lastName": lastName,
                "email": email,
                "billingAddress": billingAddress,
                "phoneNumberDialCountry": phoneNumberDialCountry,
                "phoneNumberDialCode": phoneNumberDialCode,
                "phoneNumber": phoneNumber,
            }
    
    firstName: MetaOapg.properties.firstName
    lastName: MetaOapg.properties.lastName
    billingAddress: 'CustomerUpdateDetailsRequestBillingAddress'
    email: MetaOapg.properties.email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastName"]) -> MetaOapg.properties.lastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billingAddress"]) -> 'CustomerUpdateDetailsRequestBillingAddress': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phoneNumberDialCountry"]) -> MetaOapg.properties.phoneNumberDialCountry: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phoneNumberDialCode"]) -> MetaOapg.properties.phoneNumberDialCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phoneNumber"]) -> MetaOapg.properties.phoneNumber: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["firstName", "lastName", "email", "billingAddress", "phoneNumberDialCountry", "phoneNumberDialCode", "phoneNumber", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastName"]) -> MetaOapg.properties.lastName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billingAddress"]) -> 'CustomerUpdateDetailsRequestBillingAddress': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phoneNumberDialCountry"]) -> typing.Union[MetaOapg.properties.phoneNumberDialCountry, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phoneNumberDialCode"]) -> typing.Union[MetaOapg.properties.phoneNumberDialCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phoneNumber"]) -> typing.Union[MetaOapg.properties.phoneNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["firstName", "lastName", "email", "billingAddress", "phoneNumberDialCountry", "phoneNumberDialCode", "phoneNumber", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        firstName: typing.Union[MetaOapg.properties.firstName, str, ],
        lastName: typing.Union[MetaOapg.properties.lastName, str, ],
        billingAddress: 'CustomerUpdateDetailsRequestBillingAddress',
        email: typing.Union[MetaOapg.properties.email, str, ],
        phoneNumberDialCountry: typing.Union[MetaOapg.properties.phoneNumberDialCountry, str, schemas.Unset] = schemas.unset,
        phoneNumberDialCode: typing.Union[MetaOapg.properties.phoneNumberDialCode, str, schemas.Unset] = schemas.unset,
        phoneNumber: typing.Union[MetaOapg.properties.phoneNumber, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CustomerUpdateDetailsRequest':
        return super().__new__(
            cls,
            *args,
            firstName=firstName,
            lastName=lastName,
            billingAddress=billingAddress,
            email=email,
            phoneNumberDialCountry=phoneNumberDialCountry,
            phoneNumberDialCode=phoneNumberDialCode,
            phoneNumber=phoneNumber,
            _configuration=_configuration,
            **kwargs,
        )

from billsby_python_sdk.model.customer_update_details_request_billing_address import CustomerUpdateDetailsRequestBillingAddress
