# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class InvoiceGetPaymentLogsResponseItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            paymentLogId = schemas.IntSchema
            createdOn = schemas.StrSchema
            gatewayId = schemas.IntSchema
            gatewayName = schemas.StrSchema
            reference = schemas.StrSchema
            paymentMethod = schemas.StrSchema
            status = schemas.StrSchema
            __annotations__ = {
                "paymentLogId": paymentLogId,
                "createdOn": createdOn,
                "gatewayId": gatewayId,
                "gatewayName": gatewayName,
                "reference": reference,
                "paymentMethod": paymentMethod,
                "status": status,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentLogId"]) -> MetaOapg.properties.paymentLogId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdOn"]) -> MetaOapg.properties.createdOn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gatewayId"]) -> MetaOapg.properties.gatewayId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gatewayName"]) -> MetaOapg.properties.gatewayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reference"]) -> MetaOapg.properties.reference: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentMethod"]) -> MetaOapg.properties.paymentMethod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["paymentLogId", "createdOn", "gatewayId", "gatewayName", "reference", "paymentMethod", "status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentLogId"]) -> typing.Union[MetaOapg.properties.paymentLogId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdOn"]) -> typing.Union[MetaOapg.properties.createdOn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gatewayId"]) -> typing.Union[MetaOapg.properties.gatewayId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gatewayName"]) -> typing.Union[MetaOapg.properties.gatewayName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reference"]) -> typing.Union[MetaOapg.properties.reference, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentMethod"]) -> typing.Union[MetaOapg.properties.paymentMethod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["paymentLogId", "createdOn", "gatewayId", "gatewayName", "reference", "paymentMethod", "status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        paymentLogId: typing.Union[MetaOapg.properties.paymentLogId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        createdOn: typing.Union[MetaOapg.properties.createdOn, str, schemas.Unset] = schemas.unset,
        gatewayId: typing.Union[MetaOapg.properties.gatewayId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        gatewayName: typing.Union[MetaOapg.properties.gatewayName, str, schemas.Unset] = schemas.unset,
        reference: typing.Union[MetaOapg.properties.reference, str, schemas.Unset] = schemas.unset,
        paymentMethod: typing.Union[MetaOapg.properties.paymentMethod, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InvoiceGetPaymentLogsResponseItem':
        return super().__new__(
            cls,
            *args,
            paymentLogId=paymentLogId,
            createdOn=createdOn,
            gatewayId=gatewayId,
            gatewayName=gatewayName,
            reference=reference,
            paymentMethod=paymentMethod,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
