# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class ProductCreateCycleRequestAllowancePlanInputModelItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "allowanceId",
        }
        
        class properties:
            allowanceId = schemas.Int32Schema
            isForced = schemas.BoolSchema
        
            @staticmethod
            def allowancePriceModels() -> typing.Type['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels']:
                return ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels
            __annotations__ = {
                "allowanceId": allowanceId,
                "isForced": isForced,
                "allowancePriceModels": allowancePriceModels,
            }
    
    allowanceId: MetaOapg.properties.allowanceId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowanceId"]) -> MetaOapg.properties.allowanceId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isForced"]) -> MetaOapg.properties.isForced: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowancePriceModels"]) -> 'ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["allowanceId", "isForced", "allowancePriceModels", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowanceId"]) -> MetaOapg.properties.allowanceId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isForced"]) -> typing.Union[MetaOapg.properties.isForced, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowancePriceModels"]) -> typing.Union['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["allowanceId", "isForced", "allowancePriceModels", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        allowanceId: typing.Union[MetaOapg.properties.allowanceId, decimal.Decimal, int, ],
        isForced: typing.Union[MetaOapg.properties.isForced, bool, schemas.Unset] = schemas.unset,
        allowancePriceModels: typing.Union['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProductCreateCycleRequestAllowancePlanInputModelItem':
        return super().__new__(
            cls,
            *args,
            allowanceId=allowanceId,
            isForced=isForced,
            allowancePriceModels=allowancePriceModels,
            _configuration=_configuration,
            **kwargs,
        )

from billsby_python_sdk.model.product_create_cycle_request_allowance_plan_input_model_item_allowance_price_models import ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModels
