# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiers(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem']:
            return ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem'], typing.List['ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiers':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem':
        return super().__getitem__(i)

from billsby_python_sdk.model.product_create_cycle_request_allowance_plan_input_model_item_allowance_price_models_item_unit_tiers_item import ProductCreateCycleRequestAllowancePlanInputModelItemAllowancePriceModelsItemUnitTiersItem
