# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401


class ProductUpdatePlanAndCycleRequestCycles(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Define your cycles
    """


    class MetaOapg:
        
        class properties:
            cycleId = schemas.Int32Schema
            frequency = schemas.Int32Schema
            frequencyType = schemas.Int32Schema
            price = schemas.Int32Schema
            freeTrial = schemas.Int32Schema
            freeTrialFrequencyType = schemas.Int32Schema
            setupFeePrice = schemas.Int32Schema
            freeQuantity = schemas.Int32Schema
            billingDateType = schemas.Int32Schema
            fixedBillingDateDay = schemas.Int32Schema
            proRateOption = schemas.Int32Schema
            visibility = schemas.Int32Schema
        
            @staticmethod
            def tiers() -> typing.Type['ProductUpdatePlanAndCycleRequestCyclesTiers']:
                return ProductUpdatePlanAndCycleRequestCyclesTiers
            __annotations__ = {
                "cycleId": cycleId,
                "frequency": frequency,
                "frequencyType": frequencyType,
                "price": price,
                "freeTrial": freeTrial,
                "freeTrialFrequencyType": freeTrialFrequencyType,
                "setupFeePrice": setupFeePrice,
                "freeQuantity": freeQuantity,
                "billingDateType": billingDateType,
                "fixedBillingDateDay": fixedBillingDateDay,
                "proRateOption": proRateOption,
                "visibility": visibility,
                "tiers": tiers,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cycleId"]) -> MetaOapg.properties.cycleId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["frequency"]) -> MetaOapg.properties.frequency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["frequencyType"]) -> MetaOapg.properties.frequencyType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price"]) -> MetaOapg.properties.price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["freeTrial"]) -> MetaOapg.properties.freeTrial: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["freeTrialFrequencyType"]) -> MetaOapg.properties.freeTrialFrequencyType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["setupFeePrice"]) -> MetaOapg.properties.setupFeePrice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["freeQuantity"]) -> MetaOapg.properties.freeQuantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billingDateType"]) -> MetaOapg.properties.billingDateType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fixedBillingDateDay"]) -> MetaOapg.properties.fixedBillingDateDay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["proRateOption"]) -> MetaOapg.properties.proRateOption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["visibility"]) -> MetaOapg.properties.visibility: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tiers"]) -> 'ProductUpdatePlanAndCycleRequestCyclesTiers': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cycleId", "frequency", "frequencyType", "price", "freeTrial", "freeTrialFrequencyType", "setupFeePrice", "freeQuantity", "billingDateType", "fixedBillingDateDay", "proRateOption", "visibility", "tiers", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cycleId"]) -> typing.Union[MetaOapg.properties.cycleId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["frequency"]) -> typing.Union[MetaOapg.properties.frequency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["frequencyType"]) -> typing.Union[MetaOapg.properties.frequencyType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price"]) -> typing.Union[MetaOapg.properties.price, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["freeTrial"]) -> typing.Union[MetaOapg.properties.freeTrial, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["freeTrialFrequencyType"]) -> typing.Union[MetaOapg.properties.freeTrialFrequencyType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["setupFeePrice"]) -> typing.Union[MetaOapg.properties.setupFeePrice, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["freeQuantity"]) -> typing.Union[MetaOapg.properties.freeQuantity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billingDateType"]) -> typing.Union[MetaOapg.properties.billingDateType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fixedBillingDateDay"]) -> typing.Union[MetaOapg.properties.fixedBillingDateDay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["proRateOption"]) -> typing.Union[MetaOapg.properties.proRateOption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["visibility"]) -> typing.Union[MetaOapg.properties.visibility, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tiers"]) -> typing.Union['ProductUpdatePlanAndCycleRequestCyclesTiers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cycleId", "frequency", "frequencyType", "price", "freeTrial", "freeTrialFrequencyType", "setupFeePrice", "freeQuantity", "billingDateType", "fixedBillingDateDay", "proRateOption", "visibility", "tiers", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cycleId: typing.Union[MetaOapg.properties.cycleId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        frequency: typing.Union[MetaOapg.properties.frequency, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        frequencyType: typing.Union[MetaOapg.properties.frequencyType, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        price: typing.Union[MetaOapg.properties.price, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        freeTrial: typing.Union[MetaOapg.properties.freeTrial, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        freeTrialFrequencyType: typing.Union[MetaOapg.properties.freeTrialFrequencyType, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        setupFeePrice: typing.Union[MetaOapg.properties.setupFeePrice, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        freeQuantity: typing.Union[MetaOapg.properties.freeQuantity, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        billingDateType: typing.Union[MetaOapg.properties.billingDateType, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        fixedBillingDateDay: typing.Union[MetaOapg.properties.fixedBillingDateDay, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        proRateOption: typing.Union[MetaOapg.properties.proRateOption, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        visibility: typing.Union[MetaOapg.properties.visibility, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tiers: typing.Union['ProductUpdatePlanAndCycleRequestCyclesTiers', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProductUpdatePlanAndCycleRequestCycles':
        return super().__new__(
            cls,
            *args,
            cycleId=cycleId,
            frequency=frequency,
            frequencyType=frequencyType,
            price=price,
            freeTrial=freeTrial,
            freeTrialFrequencyType=freeTrialFrequencyType,
            setupFeePrice=setupFeePrice,
            freeQuantity=freeQuantity,
            billingDateType=billingDateType,
            fixedBillingDateDay=fixedBillingDateDay,
            proRateOption=proRateOption,
            visibility=visibility,
            tiers=tiers,
            _configuration=_configuration,
            **kwargs,
        )

from billsby_python_sdk.model.product_update_plan_and_cycle_request_cycles_tiers import ProductUpdatePlanAndCycleRequestCyclesTiers
