# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomerCreateWithoutSubscriptionRequestCardDetails(TypedDict):
    pass

class OptionalCustomerCreateWithoutSubscriptionRequestCardDetails(TypedDict, total=False):
    # The full name of the customer
    fullName: str

    # This can be found in the create token API response
    paymentCardToken: str

    # Customers two digit expiry month - i.e. \"12\"
    expiryMonth: int

    # Customers card expiry year - i.e. \"2020\"
    expiryYear: int

    # \"visa\" \"master\" \"american_express\"
    cardType: str

    # The last 4 digits of the customers card
    last4Digits: str

class CustomerCreateWithoutSubscriptionRequestCardDetails(RequiredCustomerCreateWithoutSubscriptionRequestCardDetails, OptionalCustomerCreateWithoutSubscriptionRequestCardDetails):
    pass
