# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from billsby_python_sdk.type.invoice_details_response_subscriptions import InvoiceDetailsResponseSubscriptions
from billsby_python_sdk.type.invoice_details_response_taxes import InvoiceDetailsResponseTaxes

class RequiredInvoiceDetailsResponse(TypedDict):
    pass

class OptionalInvoiceDetailsResponse(TypedDict, total=False):
    invoiceId: str

    customerEmail: str

    customerFirstName: str

    customerLastName: str

    customerUniqueId: str

    addressLine1: str

    addressLine2: str

    addressPostCode: str

    addressCity: str

    addressState: str

    addressCountry: str

    addressCountryCode: str

    invoiceNumber: str

    createdOn: str

    formattedAmount: str

    amount: str

    currency: str

    status: str

    subTotal: str

    taxTotal: str

    prorationAdjustment: str

    prorationFactor: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    taxes: InvoiceDetailsResponseTaxes

    invoiceType: str

    subscriptions: InvoiceDetailsResponseSubscriptions

    companyName: str

    companyEmail: str

    companyTaxNumber: str

    companyDomain: str

    companyPhoneNumberDialCountry: str

    companyPhoneNumberDialCode: str

    companyPhoneNumber: str

    companyAddressLine1: str

    companyAddressLine2: str

    companyCity: str

    companyState: str

    companyPostCode: str

    companyCountry: str

    brandingLogo: str

    brandingLogoBackgroundColor: str

    brandingHighlightColor: str

    supportUrl: str

    cardType: str

    cardLast4Digits: str

    cardExpiryMonth: str

    cardExpiryYear: str

    refundableAmount: str

    footerCompanyName: str

    footerAddressLine1: str

    footerAddressLine2: str

    footerAddressState: str

    footerAddressCity: str

    footerAddressPostCode: str

    footerAddressCountryISO3: str

    footerEmailAddress: str

    footerPhoneNumberDialCountry: str

    footerPhoneNumberDialCode: str

    footerPhoneNumber: str

    supportContactHeading: str

    supportContactContent: str

    supportContactSupportUrl: str

    supportContactSupportUrlButtonText: str

    isAdvertEnabled: str

    advertImageUrl: str

    advertLinkToUrl: str

class InvoiceDetailsResponse(RequiredInvoiceDetailsResponse, OptionalInvoiceDetailsResponse):
    pass
