# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from billsby_python_sdk.type.product_update_plan_and_cycle_request_cycles_tiers import ProductUpdatePlanAndCycleRequestCyclesTiers

class RequiredProductUpdatePlanAndCycleRequestCycles(TypedDict):
    pass

class OptionalProductUpdatePlanAndCycleRequestCycles(TypedDict, total=False):
    # The unique identifier of the cycle in the Billsby platform
    cycleId: int

    # A number with the update frequency (for example: 5 to renew every five of frequencyType)
    frequency: int

    # Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4
    frequencyType: int

    # The price amount of this cycle (unused in tiered based cycles)
    price: int

    # A number with the amount of free trial (for example: 5 for five of frequencyType of free trial)
    freeTrial: int

    # Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4
    freeTrialFrequencyType: int

    # The price amount of setup fee (charged only on first invoice of new subscriptions)
    setupFeePrice: int

    # The amount of free units in tiered based cycles
    freeQuantity: int

    # Anniversary = 1, FixedDayEachMonth = 2, FixedDayOfTheWeek = 3
    billingDateType: int

    # The fixed billing date if there is one (from 1 to 28)
    fixedBillingDateDay: int

    # DoNotProRate = 1, DoNotChargeUntilNextCycle = 2, ProRateBasedOnDaysRemaining = 3
    proRateOption: int

    # The type of visibility of each product; public, hidden and on-sale. Available values: 0, 1, 2, 3 (Public=0, Hidden=1, Internal=2, OffSale=3)
    visibility: int

    tiers: ProductUpdatePlanAndCycleRequestCyclesTiers

class ProductUpdatePlanAndCycleRequestCycles(RequiredProductUpdatePlanAndCycleRequestCycles, OptionalProductUpdatePlanAndCycleRequestCycles):
    pass
