# coding: utf-8
"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from billsby_python_sdk.client_custom import ClientCustom
from billsby_python_sdk.configuration import Configuration
from billsby_python_sdk.api_client import ApiClient
from billsby_python_sdk.type_util import copy_signature
from billsby_python_sdk.apis.tags.addon_api import AddonApi
from billsby_python_sdk.apis.tags.allowance_api import AllowanceApi
from billsby_python_sdk.apis.tags.creditnote_api import CreditnoteApi
from billsby_python_sdk.apis.tags.custom_field_api import CustomFieldApi
from billsby_python_sdk.apis.tags.customer_api import CustomerApi
from billsby_python_sdk.apis.tags.invoice_api import InvoiceApi
from billsby_python_sdk.apis.tags.product_api import ProductApi
from billsby_python_sdk.apis.tags.subscription_api import SubscriptionApi



class Billsby(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.addon: AddonApi = AddonApi(api_client)
        self.allowance: AllowanceApi = AllowanceApi(api_client)
        self.creditnote: CreditnoteApi = CreditnoteApi(api_client)
        self.custom_field: CustomFieldApi = CustomFieldApi(api_client)
        self.customer: CustomerApi = CustomerApi(api_client)
        self.invoice: InvoiceApi = InvoiceApi(api_client)
        self.product: ProductApi = ProductApi(api_client)
        self.subscription: SubscriptionApi = SubscriptionApi(api_client)
