# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from billsby_python_sdk.pydantic.customer_add_subscription_to_existing_customer_request_add_ons import CustomerAddSubscriptionToExistingCustomerRequestAddOns
from billsby_python_sdk.pydantic.customer_add_subscription_to_existing_customer_request_address import CustomerAddSubscriptionToExistingCustomerRequestAddress
from billsby_python_sdk.pydantic.customer_add_subscription_to_existing_customer_request_coupon_codes import CustomerAddSubscriptionToExistingCustomerRequestCouponCodes
from billsby_python_sdk.pydantic.customer_add_subscription_to_existing_customer_request_custom_field_response import CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponse

class CustomerAddSubscriptionToExistingCustomerRequest(BaseModel):
    # The unique identifier of the cycle in the Billsby platform
    cycle_id: int = Field(alias='cycleId')

    # The number of units for unit based plans
    units: typing.Optional[int] = Field(None, alias='units')

    address: typing.Optional[CustomerAddSubscriptionToExistingCustomerRequestAddress] = Field(None, alias='address')

    # The shipping address of the customer
    shipping_address: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='shippingAddress')

    # Any additional email addresses given by the customer
    additional_email: typing.Optional[str] = Field(None, alias='additionalEmail')

    # The country associated with the phone number
    phone_number_dial_country: typing.Optional[str] = Field(None, alias='phoneNumberDialCountry')

    # The country dial code for the customer phone number
    phone_number_dial_code: typing.Optional[int] = Field(None, alias='phoneNumberDialCode')

    # The customer's phone number
    phone_number: typing.Optional[int] = Field(None, alias='phoneNumber')

    # Gas the customer given marketing consent: true or false
    marketing_consent: typing.Optional[bool] = Field(None, alias='marketingConsent')

    # Tax registration number
    tax_reg_number: typing.Optional[str] = Field(None, alias='taxRegNumber')

    ip_address: typing.Optional[str] = Field(None, alias='ipAddress')

    custom_field_response: typing.Optional[CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponse] = Field(None, alias='customFieldResponse')

    add_ons: typing.Optional[CustomerAddSubscriptionToExistingCustomerRequestAddOns] = Field(None, alias='addOns')

    # Any allowances to be included with the plan
    allowances: typing.Optional[int] = Field(None, alias='allowances')

    coupon_codes: typing.Optional[CustomerAddSubscriptionToExistingCustomerRequestCouponCodes] = Field(None, alias='couponCodes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
