# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from billsby_python_sdk.pydantic.customer_create_without_subscription_request_card_details import CustomerCreateWithoutSubscriptionRequestCardDetails

class CustomerCreateWithoutSubscriptionRequest(BaseModel):
    address_line1: str = Field(alias='addressLine1')

    city: str = Field(alias='city')

    state: str = Field(alias='state')

    country: str = Field(alias='country')

    post_code: str = Field(alias='postCode')

    first_name: str = Field(alias='firstName')

    last_name: str = Field(alias='lastName')

    email: str = Field(alias='email')

    address_line2: typing.Optional[str] = Field(None, alias='addressLine2')

    card_details: typing.Optional[CustomerCreateWithoutSubscriptionRequestCardDetails] = Field(None, alias='cardDetails')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
