# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from billsby_python_sdk.pydantic.customer_update_details_request_billing_address import CustomerUpdateDetailsRequestBillingAddress

class CustomerUpdateDetailsRequest(BaseModel):
    # The customers first name
    first_name: str = Field(alias='firstName')

    # The customers last name
    last_name: str = Field(alias='lastName')

    # The email address we have on file for the customer
    email: str = Field(alias='email')

    billing_address: CustomerUpdateDetailsRequestBillingAddress = Field(alias='billingAddress')

    # The customers phone number dial country (i.e. \"UK\")
    phone_number_dial_country: typing.Optional[str] = Field(None, alias='phoneNumberDialCountry')

    # The customer phone number dial code
    phone_number_dial_code: typing.Optional[str] = Field(None, alias='phoneNumberDialCode')

    # The phone number we have on file for the customer. Remove \"0\" from the start.
    phone_number: typing.Optional[str] = Field(None, alias='phoneNumber')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
