# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CustomerCreateWithoutSubscriptionRequestCardDetails(BaseModel):
    # The full name of the customer
    full_name: typing.Optional[str] = Field(None, alias='fullName')

    # This can be found in the create token API response
    payment_card_token: typing.Optional[str] = Field(None, alias='paymentCardToken')

    # Customers two digit expiry month - i.e. \"12\"
    expiry_month: typing.Optional[int] = Field(None, alias='expiryMonth')

    # Customers card expiry year - i.e. \"2020\"
    expiry_year: typing.Optional[int] = Field(None, alias='expiryYear')

    # \"visa\" \"master\" \"american_express\"
    card_type: typing.Optional[str] = Field(None, alias='cardType')

    # The last 4 digits of the customers card
    last4_digits: typing.Optional[str] = Field(None, alias='last4Digits')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
