# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from billsby_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from billsby_python_sdk.api_response import AsyncGeneratorResponse
from billsby_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from billsby_python_sdk import schemas  # noqa: F401

from billsby_python_sdk.model.product_update_plan_and_cycle_request import ProductUpdatePlanAndCycleRequest as ProductUpdatePlanAndCycleRequestSchema
from billsby_python_sdk.model.product_update_plan_and_cycle_request_cycles import ProductUpdatePlanAndCycleRequestCycles as ProductUpdatePlanAndCycleRequestCyclesSchema

from billsby_python_sdk.type.product_update_plan_and_cycle_request_cycles import ProductUpdatePlanAndCycleRequestCycles
from billsby_python_sdk.type.product_update_plan_and_cycle_request import ProductUpdatePlanAndCycleRequest

from ...api_client import Dictionary
from billsby_python_sdk.pydantic.product_update_plan_and_cycle_request_cycles import ProductUpdatePlanAndCycleRequestCycles as ProductUpdatePlanAndCycleRequestCyclesPydantic
from billsby_python_sdk.pydantic.product_update_plan_and_cycle_request import ProductUpdatePlanAndCycleRequest as ProductUpdatePlanAndCycleRequestPydantic

# Path params
CompanyDomainSchema = schemas.StrSchema
ProductIdSchema = schemas.Int32Schema
PlanIdSchema = schemas.Int32Schema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyDomain': typing.Union[CompanyDomainSchema, str, ],
        'productId': typing.Union[ProductIdSchema, decimal.Decimal, int, ],
        'planId': typing.Union[PlanIdSchema, decimal.Decimal, int, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_domain = api_client.PathParameter(
    name="companyDomain",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyDomainSchema,
    required=True,
)
request_path_product_id = api_client.PathParameter(
    name="productId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ProductIdSchema,
    required=True,
)
request_path_plan_id = api_client.PathParameter(
    name="planId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=PlanIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = ProductUpdatePlanAndCycleRequestSchema


request_body_product_update_plan_and_cycle_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
SchemaFor200ResponseBodyApplicationJson = schemas.StrSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: str


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: str


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_plan_and_cycle_mapped_args(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if description is not None:
            _body["description"] = description
        if name is not None:
            _body["name"] = name
        if display_name is not None:
            _body["displayName"] = display_name
        if feature_tags is not None:
            _body["featureTags"] = feature_tags
        if visibility is not None:
            _body["visibility"] = visibility
        if cycles is not None:
            _body["cycles"] = cycles
        if redirect_url is not None:
            _body["redirectUrl"] = redirect_url
        if alert_email is not None:
            _body["alertEmail"] = alert_email
        args.body = _body
        if company_domain is not None:
            _path_params["companyDomain"] = company_domain
        if product_id is not None:
            _path_params["productId"] = product_id
        if plan_id is not None:
            _path_params["planId"] = plan_id
        args.path = _path_params
        return args

    async def _aupdate_plan_and_cycle_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Update a plan and cycle
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_domain,
            request_path_product_id,
            request_path_plan_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/{companyDomain}/products/{productId}/plans/{planId}',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_product_update_plan_and_cycle_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_plan_and_cycle_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Update a plan and cycle
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_domain,
            request_path_product_id,
            request_path_plan_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/{companyDomain}/products/{productId}/plans/{planId}',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_product_update_plan_and_cycle_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdatePlanAndCycleRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_plan_and_cycle(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_plan_and_cycle_mapped_args(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
        )
        return await self._aupdate_plan_and_cycle_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def update_plan_and_cycle(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_plan_and_cycle_mapped_args(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
        )
        return self._update_plan_and_cycle_oapg(
            body=args.body,
            path_params=args.path,
        )

class UpdatePlanAndCycle(BaseApi):

    async def aupdate_plan_and_cycle(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> str:
        raw_response = await self.raw.aupdate_plan_and_cycle(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
            **kwargs,
        )
        if validate:
            return RootModel[str](raw_response.body).root
        return raw_response.body
    
    
    def update_plan_and_cycle(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
        validate: bool = False,
    ) -> str:
        raw_response = self.raw.update_plan_and_cycle(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
        )
        if validate:
            return RootModel[str](raw_response.body).root
        return raw_response.body


class ApiForput(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aput(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_plan_and_cycle_mapped_args(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
        )
        return await self._aupdate_plan_and_cycle_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def put(
        self,
        company_domain: str,
        product_id: int,
        plan_id: int,
        description: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        display_name: typing.Optional[str] = None,
        feature_tags: typing.Optional[str] = None,
        visibility: typing.Optional[int] = None,
        cycles: typing.Optional[ProductUpdatePlanAndCycleRequestCycles] = None,
        redirect_url: typing.Optional[str] = None,
        alert_email: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_plan_and_cycle_mapped_args(
            company_domain=company_domain,
            product_id=product_id,
            plan_id=plan_id,
            description=description,
            name=name,
            display_name=display_name,
            feature_tags=feature_tags,
            visibility=visibility,
            cycles=cycles,
            redirect_url=redirect_url,
            alert_email=alert_email,
        )
        return self._update_plan_and_cycle_oapg(
            body=args.body,
            path_params=args.path,
        )

