# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_subscriptions.post import AddSubscriptionToExistingCustomer
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_gdprcleanup.put import ClearGdprData
from billsby_python_sdk.paths.company_domain_subscriptions.post import CreateNewCustomerAndSubscription
from billsby_python_sdk.paths.company_domain_customers.post import CreateWithoutSubscription
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id.delete import DeleteById
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_credit_notes.get import GetCreditNotes
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id.get import GetDetails
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_subscriptions_featuretags.get import GetFeatureTags
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_subscriptions.get import GetSubscriptionsByUniqueId
from billsby_python_sdk.paths.company_domain_customers.get import ListCustomers
from billsby_python_sdk.paths.company_domain_customfield_responses_custom_field_response_id.put import UpdateCustomFieldResponse
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id.put import UpdateDetails
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_payment_card.put import UpdatePaymentCardToken
from billsby_python_sdk.paths.company_domain_customers_customer_unique_id_paymentdetailsrequest.get import UpdatePaymentDetailsRequest
from billsby_python_sdk.apis.tags.customer_api_raw import CustomerApiRaw


class CustomerApi(
    AddSubscriptionToExistingCustomer,
    ClearGdprData,
    CreateNewCustomerAndSubscription,
    CreateWithoutSubscription,
    DeleteById,
    GetCreditNotes,
    GetDetails,
    GetFeatureTags,
    GetSubscriptionsByUniqueId,
    ListCustomers,
    UpdateCustomFieldResponse,
    UpdateDetails,
    UpdatePaymentCardToken,
    UpdatePaymentDetailsRequest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CustomerApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CustomerApiRaw(api_client)
