# coding: utf-8

"""
    Billsby API

    Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

    The version of the OpenAPI document: 1.3.5
    Generated by: https://konfigthis.com
"""

from billsby_python_sdk.paths.company_domain_products_product_id_plans_plan_id_cycles.post import CreateCycle
from billsby_python_sdk.paths.company_domain_products.post import CreateNewProduct
from billsby_python_sdk.paths.company_domain_products_product_id_plans.post import CreatePlan
from billsby_python_sdk.paths.company_domain_products_product_id.get import GetDetails
from billsby_python_sdk.paths.company_domain_products_product_id_plans.get import ListPlans
from billsby_python_sdk.paths.company_domain_products.get import ListProducts
from billsby_python_sdk.paths.company_domain_products_product_id_plans_plan_id.put import UpdatePlanAndCycle
from billsby_python_sdk.paths.company_domain_products_product_id_plans_orders.put import UpdatePlanOrder
from billsby_python_sdk.paths.company_domain_products_product_id.put import UpdateProduct
from billsby_python_sdk.apis.tags.product_api_raw import ProductApiRaw


class ProductApi(
    CreateCycle,
    CreateNewProduct,
    CreatePlan,
    GetDetails,
    ListPlans,
    ListProducts,
    UpdatePlanAndCycle,
    UpdatePlanOrder,
    UpdateProduct,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProductApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProductApiRaw(api_client)
